[server]
maxUploadSize = 50
enableCORS = false
enableWebsocketCompression = false
headless = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[theme]
base = "light"
primaryColor = "#ff6b6b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
